### PR TITLE
Ignore build folder in git

### PR DESCRIPTION
**Pull request by kevin940726**
Instead we should develop in `master` branch and force push `build/` folder to `gh-pages` branch.

### CODE REVIEW

**Comment by scars377** [comment]
can you show me how the command should be?

**Comment by jasperck** [comment]
Like this https://gist.github.com/cobyism/4730490?

**Comment by kevin940726** [comment]
@jasperck Yep, like that. Also we should always perform a force push to bypass the heavy diff of build files.

**Comment by scars377** [comment]
thanks a lot! will do.

**Pull request closed without merging**
